- name: "SCORED | 1.10 | Ensure system-wide crypto policy is not legacy"
  block:
    - name: Check Crypto Policy
      slurp:
        src: /etc/crypto-policies/config
      register: cryptopolicies

    - name: Update if not correct
      command: update-crypto-policies --set DEFAULT
      when:
        - '"LEGACY" in cryptopolicies.content|b64decode'
  when:
    - rhel8cis_rule_1_10
  tags:
    - level1
    - level2
    - rule_1.10
